---
# config section
#
driver:
  name: vagrant                           ## Vagrant as virtualisation platform.
                                          ## Provided by kitchen-vagrant.
platforms:
  - name: centos-7.2
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-7.2-64-nocm  ## CentOS 7.2 Vagrant machine image.

provisioner:
  name: ansible_playbook                  ## Ansible as the "provisioner".
  hosts: test-kitchen                     ## Provided by the kitchen-ansible project.
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false

verifier:
  name: serverspec                        ## Use Serverspec as the "verifier"
  bundler_path: '/usr/local/bin'          ## (test language or framework).
  rspec_path: '/usr/local/bin'            ## Provided by the kitchen-verifier-serverspec project.

# test suites
#
suites:
  - name: master
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/master/serverspec/master_spec.rb  ## An actual test suite.
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.10'}]
  - name: slave1
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave1/serverspec/slave1_spec.rb
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.11'}]
  - name: slave2
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave2/serverspec/slave2_spec.rb
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.12'}]
