---
# .kitchen.local.yml:
# ---
# driver:
#   region: ap-southeast-2
#   subnet_id: subnet-1234567890abcdef0
#   aws_ssh_key_id: default
#   tags:
#     foo: bar
#     baz: qux

driver:
  name: ec2
  instance_type: t2.micro

transport:
  ssh_key: ~/.ssh/default.pem

platforms:
  - name: centos-7.4
    driver:
      image_id: ami-0acb51609b44c296b

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false

verifier:
  name: serverspec
  bundler_path: '/usr/local/bin'
  rspec_path: '/usr/local/bin'

suites:
  - name: master
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/master/serverspec/master_spec.rb
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.10'}]
  - name: slave1
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave1/serverspec/slave1_spec.rb
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.11'}]
  - name: slave2
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave2/serverspec/slave2_spec.rb
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.12'}]
