---
driver:
  name: vagrant

platforms:
  - name: centos-7.2
    driver_plugin: vagrant
    driver_config:
      box: puppetlabs/centos-7.2-64-nocm

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_verbosity: 2
  require_ansible_repo: false
  require_ansible_omnibus: true
  require_chef_for_busser: false

verifier:
  name: serverspec

suites:
  - name: master
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/master/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.10'}]
  - name: slave1
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave1/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.11'}]
  - name: slave2
    verifier:
      patterns:
        - roles/ansible-bind/test/integration/slave2/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
    driver_config:
      network:
        - ['private_network', {ip: '10.0.0.12'}]
